version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mittpassord
      MYSQL_DATABASE: bilinfo
      MYSQL_USER: user
      MYSQL_PASSWORD: mittpassord
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
